module.exports = [
  // ==================== NIVEL 1: Lógica y pensamiento algorítmico ====================
  {
    id: "n1_001",
    nivel: 1,
    tipo: "opcion_multiple",
    dificultad: "inicio",
    titulo: "¿Qué es un algoritmo?",
    enunciado: "Un algoritmo es una secuencia de pasos para resolver un problema. ¿Cuál de las siguientes opciones describe MEJOR un algoritmo?",
    opciones: [
      "A) Un programa de computadora en Python",
      "B) Una serie de instrucciones ordenadas para resolver un problema",
      "C) Un lenguaje de programación",
      "D) Una base de datos"
    ],
    respuestaCorrecta: "B",
    xp: 10,
    feedbackCorrecto: "✅ ¡Exacto! Un algoritmo es una secuencia de pasos definidos y ordenados para resolver un problema, independiente del lenguaje.",
    feedbackIncorrecto: "❌ Un algoritmo no es código específico ni un lenguaje. Es la LÓGICA detrás de la solución, como una receta de cocina.",
    pista: "Piensa en una receta de cocina: lista de pasos ordenados para llegar a un resultado."
  },
  {
    id: "n1_002",
    nivel: 1,
    tipo: "opcion_multiple",
    dificultad: "inicio",
    titulo: "Orden correcto",
    enunciado: "Quieres hacer una taza de té. ¿Cuál es el orden lógico correcto?",
    opciones: [
      "A) Hervir agua → Poner bolsita → Servir → Esperar",
      "B) Poner bolsita → Hervir agua → Servir → Esperar",
      "C) Hervir agua → Poner bolsita → Esperar → Servir",
      "D) Servir → Hervir agua → Poner bolsita → Esperar"
    ],
    respuestaCorrecta: "C",
    xp: 10,
    feedbackCorrecto: "✅ ¡Correcto! El orden importa: hervir agua → poner bolsita → esperar a que infusione → servir.",
    feedbackIncorrecto: "❌ Recuerda: primero el agua debe estar caliente, luego la bolsita infusiona, y al final sirves.",
    pista: "El agua debe estar lista ANTES de poner la bolsita."
  },
  {
    id: "n1_003",
    nivel: 1,
    tipo: "completar",
    dificultad: "medio",
    titulo: "Diagrama de flujo",
    enunciado: "En un diagrama de flujo, el símbolo de DECISIÓN tiene forma de:",
    opciones: ["Rectángulo", "Rombo", "Óvalo", "Triángulo"],
    respuestaCorrecta: "Rombo",
    xp: 15,
    feedbackCorrecto: "✅ ¡Correcto! El rombo (diamante) representa una decisión con caminos SÍ/NO.",
    feedbackIncorrecto: "❌ El símbolo de decisión es el ROMBO (diamante). El rectángulo es para procesos, el óvalo para inicio/fin.",
    pista: "Tiene forma de diamante y tiene dos salidas: una para SÍ y otra para NO."
  },
  {
    id: "n1_004",
    nivel: 1,
    tipo: "ordenar",
    dificultad: "medio",
    titulo: "Ordena el algoritmo",
    enunciado: "Ordena los pasos para calcular el área de un rectángulo:",
    items: [
      "Mostrar el resultado",
      "Leer el largo",
      "Calcular: área = largo × ancho",
      "Leer el ancho"
    ],
    respuestaCorrecta: [1, 3, 2, 0],
    xp: 20,
    feedbackCorrecto: "✅ ¡Perfecto! Primero lees los datos, luego calculas, luego muestras el resultado.",
    feedbackIncorrecto: "❌ El orden correcto es: Leer largo → Leer ancho → Calcular área → Mostrar resultado.",
    pista: "Siempre: Entrada → Proceso → Salida"
  },
  {
    id: "n1_005",
    nivel: 1,
    tipo: "opcion_multiple",
    dificultad: "avanzado",
    titulo: "Pseudocódigo",
    enunciado: "¿Qué hace este pseudocódigo?\n\nSI edad >= 18 ENTONCES\n  mostrar('Mayor de edad')\nSINO\n  mostrar('Menor de edad')\nFIN SI",
    opciones: [
      "A) Suma dos números",
      "B) Verifica si alguien puede votar según su edad",
      "C) Calcula el promedio de edades",
      "D) Muestra siempre 'Mayor de edad'"
    ],
    respuestaCorrecta: "B",
    xp: 25,
    feedbackCorrecto: "✅ ¡Excelente! El pseudocódigo evalúa si la edad es mayor o igual a 18 para clasificar como mayor o menor de edad.",
    feedbackIncorrecto: "❌ Hay una condición SI/SINO que evalúa la edad. Si es ≥18 muestra una cosa, sino muestra otra.",
    pista: "Lee el SI (condición) y los dos caminos posibles."
  },

  // ==================== NIVEL 2: Entrada, salida y tipos de datos ====================
  {
    id: "n2_001",
    nivel: 2,
    tipo: "opcion_multiple",
    dificultad: "inicio",
    titulo: "Función print()",
    enunciado: "¿Qué hace print('Hola Mundo') en Python?",
    opciones: [
      "A) Guarda 'Hola Mundo' en una variable",
      "B) Muestra 'Hola Mundo' en la pantalla",
      "C) Lee 'Hola Mundo' del teclado",
      "D) Crea un archivo llamado Hola Mundo"
    ],
    respuestaCorrecta: "B",
    xp: 10,
    feedbackCorrecto: "✅ ¡Correcto! print() muestra texto en la consola/pantalla. Es la función de SALIDA más básica.",
    feedbackIncorrecto: "❌ print() = imprimir en pantalla (SALIDA). No guarda, no lee del teclado.",
    pista: "print = imprimir. ¿Imprimir dónde? En la pantalla."
  },
  {
    id: "n2_002",
    nivel: 2,
    tipo: "opcion_multiple",
    dificultad: "inicio",
    titulo: "Función input()",
    enunciado: "¿Cuál es el ERROR en este código?\n\nprint(input('¿Cuál es tu nombre? '))",
    opciones: [
      "A) No hay error, el código es correcto pero confuso",
      "B) print va dentro de input, no al revés",
      "C) input() no existe en Python",
      "D) Falta un punto y coma al final"
    ],
    respuestaCorrecta: "A",
    xp: 15,
    feedbackCorrecto: "✅ ¡Correcto! El código funciona: input() lee el nombre, y ese valor lo recibe print() para mostrarlo. Aunque es mejor guardarlo en variable primero.",
    feedbackIncorrecto: "❌ El código SÍ funciona. input() devuelve lo que escribe el usuario, y print() lo muestra. El orden es correcto aquí.",
    pista: "¿Qué devuelve input()? ¿Qué recibe print()?"
  },
  {
    id: "n2_003",
    nivel: 2,
    tipo: "completar",
    dificultad: "inicio",
    titulo: "Tipos de datos",
    enunciado: "nombre = 'Ana'\nedad = 20\naltura = 1.65\nesEstudiante = True\n\n¿De qué tipo es la variable 'edad'?",
    opciones: ["str", "int", "float", "bool"],
    respuestaCorrecta: "int",
    xp: 10,
    feedbackCorrecto: "✅ ¡Exacto! Los números enteros (sin decimales) son tipo int (integer).",
    feedbackIncorrecto: "❌ 'edad = 20' → 20 es un número entero, por eso es tipo int. Si fuera 20.5 sería float.",
    pista: "¿Tiene decimales? No → int. ¿Sí? → float"
  },
  {
    id: "n2_004",
    nivel: 2,
    tipo: "escribir",
    dificultad: "medio",
    titulo: "Tu primer input",
    enunciado: "Escribe el código Python para:\n1. Pedir el nombre del usuario con el mensaje: ¿Cómo te llamas?\n2. Guardarlo en la variable 'nombre'\n\n(Solo esa línea, sin print)",
    respuestaCorrecta: "nombre = input('¿Cómo te llamas?')",
    xp: 20,
    feedbackCorrecto: "✅ ¡Perfecto! Esa es la sintaxis correcta para leer entrada del usuario.",
    feedbackIncorrecto: "❌ La estructura es: variable = input('mensaje')",
    pista: "nombre = input('...mensaje...')"
  },
  {
    id: "n2_005",
    nivel: 2,
    tipo: "opcion_multiple",
    dificultad: "medio",
    titulo: "Conversión de tipos",
    enunciado: "edad = input('Escribe tu edad: ')\nedad_siguiente = edad + 1\n\n¿Qué ocurrirá al ejecutar esto?",
    opciones: [
      "A) Muestra la edad correctamente más 1",
      "B) Error: no se puede sumar str con int",
      "C) Muestra '211' si la edad es 21",
      "D) No hace nada"
    ],
    respuestaCorrecta: "B",
    xp: 25,
    feedbackCorrecto: "✅ ¡Correcto! input() SIEMPRE retorna un string. No puedes sumar string + int. Necesitas int(edad) primero.",
    feedbackIncorrecto: "❌ input() retorna string. 'edad' es un texto como '21', no el número 21. Python no puede sumar '21' + 1.",
    pista: "input() siempre retorna texto (str). Para operar matemáticamente necesitas convertirlo."
  },
  {
    id: "n2_006",
    nivel: 2,
    tipo: "completar",
    dificultad: "avanzado",
    titulo: "Concatenación",
    enunciado: "nombre = 'María'\nedad = 19\nprint('Me llamo ' + nombre + ' y tengo ' + ___ + ' años')\n\n¿Qué va en el espacio para que funcione?",
    opciones: ["edad", "str(edad)", "int(edad)", "float(edad)"],
    respuestaCorrecta: "str(edad)",
    xp: 25,
    feedbackCorrecto: "✅ ¡Exacto! Para concatenar (+) con strings, todos deben ser strings. str(edad) convierte el int 19 a '19'.",
    feedbackIncorrecto: "❌ edad es int (19). Para concatenar con strings usando +, debes convertirlo: str(edad).",
    pista: "Concatenar strings con + requiere que TODOS sean strings."
  },

  // ==================== NIVEL 3: Condicionales y decisiones ====================
  {
    id: "n3_001",
    nivel: 3,
    tipo: "opcion_multiple",
    dificultad: "inicio",
    titulo: "if básico",
    enunciado: "nota = 14\nif nota >= 11:\n    print('Aprobado')\n\n¿Qué muestra este código?",
    opciones: ["Aprobado", "Desaprobado", "Nada", "Error"],
    respuestaCorrecta: "Aprobado",
    xp: 10,
    feedbackCorrecto: "✅ ¡Correcto! 14 >= 11 es True, por lo tanto se ejecuta el print('Aprobado').",
    feedbackIncorrecto: "❌ La condición es nota >= 11. Como nota=14 y 14>=11 es verdadero, SÍ entra al if.",
    pista: "Evalúa: ¿14 es mayor o igual a 11?"
  },
  {
    id: "n3_002",
    nivel: 3,
    tipo: "completar",
    dificultad: "inicio",
    titulo: "if-else",
    enunciado: "temperatura = 35\nif temperatura > 30:\n    print('Hace calor')\n___:\n    print('Temperatura normal')\n\n¿Qué palabra va en el espacio?",
    opciones: ["elif", "else", "then", "endif"],
    respuestaCorrecta: "else",
    xp: 10,
    feedbackCorrecto: "✅ ¡Correcto! 'else' captura todos los casos donde la condición del if es False.",
    feedbackIncorrecto: "❌ En Python: if → elif (más condiciones) → else (lo demás). Para el caso contrario se usa 'else'.",
    pista: "if → ... → else. El else captura todo lo que no cumple el if."
  },
  {
    id: "n3_003",
    nivel: 3,
    tipo: "opcion_multiple",
    dificultad: "medio",
    titulo: "Operadores lógicos",
    enunciado: "edad = 17\ntiene_permiso = True\n\nif edad >= 18 or tiene_permiso:\n    print('Puede entrar')\nelse:\n    print('No puede entrar')\n\n¿Qué muestra?",
    opciones: ["Puede entrar", "No puede entrar", "Error", "Nada"],
    respuestaCorrecta: "Puede entrar",
    xp: 20,
    feedbackCorrecto: "✅ ¡Correcto! Con OR basta que UNA condición sea True. tiene_permiso=True hace que toda la expresión sea True.",
    feedbackIncorrecto: "❌ El operador OR: si CUALQUIERA es True, el resultado es True. tiene_permiso=True → puede entrar.",
    pista: "OR: al menos una debe ser True. AND: ambas deben ser True."
  },
  {
    id: "n3_004",
    nivel: 3,
    tipo: "escribir",
    dificultad: "medio",
    titulo: "Escribe el condicional",
    enunciado: "Escribe una condición if en Python que verifique si la variable 'nota' es mayor o igual a 11. Si sí, imprime 'Aprobado'.\n\n(Escribe solo las 2 líneas del if)",
    respuestaCorrecta: "if nota >= 11:\n    print('Aprobado')",
    xp: 25,
    feedbackCorrecto: "✅ ¡Excelente! Esa es la sintaxis perfecta. Recuerda el : al final del if y la indentación.",
    feedbackIncorrecto: "❌ Estructura: if condición:\n    acción_indentada",
    pista: "if nota >= 11:\n    print('...')"
  },
  {
    id: "n3_005",
    nivel: 3,
    tipo: "opcion_multiple",
    dificultad: "avanzado",
    titulo: "elif encadenado",
    enunciado: "nota = 15\nif nota >= 18:\n    print('Excelente')\nelif nota >= 14:\n    print('Bueno')\nelif nota >= 11:\n    print('Aprobado')\nelse:\n    print('Desaprobado')\n\n¿Qué imprime?",
    opciones: ["Excelente", "Bueno", "Aprobado", "Desaprobado"],
    respuestaCorrecta: "Bueno",
    xp: 30,
    feedbackCorrecto: "✅ ¡Perfecto! 15 no es >=18, pero SÍ es >=14, entonces entra al primer elif.",
    feedbackIncorrecto: "❌ Python evalúa de arriba a abajo: 15>=18? No. 15>=14? SÍ → 'Bueno'. Se detiene ahí.",
    pista: "Python evalúa en orden. La primera condición verdadera gana."
  },

  // ==================== NIVEL 4: Bucles e iteraciones ====================
  {
    id: "n4_001",
    nivel: 4,
    tipo: "opcion_multiple",
    dificultad: "inicio",
    titulo: "Bucle for básico",
    enunciado: "for i in range(3):\n    print(i)\n\n¿Qué valores imprime?",
    opciones: ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3", "1, 2"],
    respuestaCorrecta: "0, 1, 2",
    xp: 15,
    feedbackCorrecto: "✅ ¡Correcto! range(3) genera 0, 1, 2. Empieza en 0 y llega hasta 3 (sin incluirlo).",
    feedbackIncorrecto: "❌ range(n) empieza en 0 y termina en n-1. range(3) = 0, 1, 2.",
    pista: "range(3) = [0, 1, 2]. Siempre empieza en 0."
  },
  {
    id: "n4_002",
    nivel: 4,
    tipo: "completar",
    dificultad: "inicio",
    titulo: "while loop",
    enunciado: "contador = 0\n___ contador < 5:\n    print(contador)\n    contador += 1\n\n¿Qué palabra va en el espacio?",
    opciones: ["for", "while", "if", "loop"],
    respuestaCorrecta: "while",
    xp: 15,
    feedbackCorrecto: "✅ ¡Correcto! 'while' repite el bloque MIENTRAS la condición sea True.",
    feedbackIncorrecto: "❌ Para repetir mientras se cumpla una condición, usamos 'while'.",
    pista: "while = mientras. Repite mientras la condición sea True."
  },
  {
    id: "n4_003",
    nivel: 4,
    tipo: "opcion_multiple",
    dificultad: "medio",
    titulo: "¿Cuántas veces?",
    enunciado: "suma = 0\nfor i in range(1, 6):\n    suma += i\nprint(suma)\n\n¿Qué imprime?",
    opciones: ["10", "15", "21", "6"],
    respuestaCorrecta: "15",
    xp: 20,
    feedbackCorrecto: "✅ ¡Exacto! range(1,6) = 1,2,3,4,5. Suma = 1+2+3+4+5 = 15.",
    feedbackIncorrecto: "❌ range(1, 6) = 1, 2, 3, 4, 5. Suma acumulada: 1+2+3+4+5 = 15.",
    pista: "range(1, 6) va de 1 hasta 5 (no incluye 6)."
  },
  {
    id: "n4_004",
    nivel: 4,
    tipo: "escribir",
    dificultad: "medio",
    titulo: "Escribe el bucle",
    enunciado: "Escribe un bucle for en Python que imprima los números del 1 al 5 (incluyendo ambos).\n\nUsa range() correctamente.",
    respuestaCorrecta: "for i in range(1, 6):\n    print(i)",
    xp: 25,
    feedbackCorrecto: "✅ ¡Perfecto! range(1, 6) genera 1,2,3,4,5. ¡Excelente uso del bucle!",
    feedbackIncorrecto: "❌ Para del 1 al 5: range(1, 6). El segundo argumento es excluido.",
    pista: "for i in range(inicio, fin_exclusivo):"
  },
  {
    id: "n4_005",
    nivel: 4,
    tipo: "opcion_multiple",
    dificultad: "avanzado",
    titulo: "Bucle con lista",
    enunciado: "notas = [14, 8, 16, 11, 9]\naprobados = 0\nfor nota in notas:\n    if nota >= 11:\n        aprobados += 1\nprint(aprobados)\n\n¿Qué imprime?",
    opciones: ["2", "3", "4", "5"],
    respuestaCorrecta: "3",
    xp: 30,
    feedbackCorrecto: "✅ ¡Excelente! 14>=11 ✓, 8>=11 ✗, 16>=11 ✓, 11>=11 ✓, 9>=11 ✗ → 3 aprobados.",
    feedbackIncorrecto: "❌ Revisa cada nota: 14✓, 8✗, 16✓, 11✓, 9✗. Contando las que son >=11: 3.",
    pista: "Cuenta cuántas notas son >= 11 en la lista."
  },

  // ==================== NIVEL 5: Mini proyectos integradores ====================
  {
    id: "n5_001",
    nivel: 5,
    tipo: "opcion_multiple",
    dificultad: "inicio",
    titulo: "Función con retorno",
    enunciado: "def calcular_promedio(notas):\n    suma = sum(notas)\n    return suma / len(notas)\n\nresultado = calcular_promedio([14, 16, 12])\nprint(resultado)\n\n¿Qué imprime?",
    opciones: ["42", "14.0", "3", "Error"],
    respuestaCorrecta: "14.0",
    xp: 30,
    feedbackCorrecto: "✅ ¡Perfecto! sum([14,16,12])=42, len=3, 42/3=14.0",
    feedbackIncorrecto: "❌ sum([14,16,12]) = 42. len([14,16,12]) = 3. 42/3 = 14.0",
    pista: "sum() suma todos los elementos. len() cuenta cuántos hay."
  },
  {
    id: "n5_002",
    nivel: 5,
    tipo: "completar",
    dificultad: "medio",
    titulo: "Función definición",
    enunciado: "Completa el código para definir una función llamada 'saludar' que recibe 'nombre' como parámetro:\n\n___ saludar(nombre):\n    print('Hola, ' + nombre)",
    opciones: ["function", "def", "fun", "define"],
    respuestaCorrecta: "def",
    xp: 20,
    feedbackCorrecto: "✅ ¡Correcto! En Python las funciones se definen con 'def'.",
    feedbackIncorrecto: "❌ Python usa 'def' para definir funciones. Otros lenguajes usan 'function', 'fun', etc.",
    pista: "def nombre_funcion(parametros):"
  },
  {
    id: "n5_003",
    nivel: 5,
    tipo: "opcion_multiple",
    dificultad: "medio",
    titulo: "Proyecto: Calculadora de notas",
    enunciado: "Tienes este programa:\n\ndef estado(nota):\n    if nota >= 11:\n        return 'Aprobado'\n    else:\n        return 'Desaprobado'\n\nnotas = [14, 9, 11, 7, 15]\nfor n in notas:\n    print(n, '-', estado(n))\n\n¿Cuántas veces imprime 'Aprobado'?",
    opciones: ["2", "3", "4", "5"],
    respuestaCorrecta: "3",
    xp: 35,
    feedbackCorrecto: "✅ ¡Excelente! 14✓ Aprobado, 9✗, 11✓ Aprobado, 7✗, 15✓ Aprobado → 3 veces.",
    feedbackIncorrecto: "❌ Evalúa cada nota con estado(): 14≥11✓, 9<11✗, 11≥11✓, 7<11✗, 15≥11✓ → 3 aprobados.",
    pista: "La función estado() retorna 'Aprobado' si nota>=11."
  },
  {
    id: "n5_004",
    nivel: 5,
    tipo: "escribir",
    dificultad: "avanzado",
    titulo: "Escribe la función",
    enunciado: "Escribe una función llamada 'es_par' que recibe un número 'n' y retorna True si es par, False si no.\n\n(Usa el operador % para el módulo)",
    respuestaCorrecta: "def es_par(n):\n    return n % 2 == 0",
    xp: 40,
    feedbackCorrecto: "✅ ¡Brillante! n % 2 == 0 es la forma pythónica de verificar paridad.",
    feedbackIncorrecto: "❌ Un número es par si el resto de dividirlo entre 2 es 0: n % 2 == 0",
    pista: "Par = divisible entre 2. En código: n % 2 == 0"
  },
  {
    id: "n5_005",
    nivel: 5,
    tipo: "opcion_multiple",
    dificultad: "avanzado",
    titulo: "Proyecto Final: Detector de riesgo",
    enunciado: "def riesgo_academico(notas):\n    promedio = sum(notas) / len(notas)\n    reprobadas = sum(1 for n in notas if n < 11)\n    if promedio < 11 or reprobadas >= 3:\n        return 'ALERTA: Riesgo alto'\n    elif promedio < 13:\n        return 'Observación'\n    else:\n        return 'Regular'\n\nprint(riesgo_academico([8, 10, 9, 12, 11]))\n\n¿Qué imprime?",
    opciones: [
      "ALERTA: Riesgo alto",
      "Observación",
      "Regular",
      "Error"
    ],
    respuestaCorrecta: "ALERTA: Riesgo alto",
    xp: 50,
    feedbackCorrecto: "✅ ¡Increíble análisis! promedio=(8+10+9+12+11)/5=10. 10<11 → ALERTA. ¡Eres un master del código!",
    feedbackIncorrecto: "❌ promedio = (8+10+9+12+11)/5 = 50/5 = 10. Como 10 < 11, la primera condición es True → ALERTA.",
    pista: "Calcula el promedio primero: (8+10+9+12+11)/5 = ?"
  }
];
